Traceback (most recent call last):
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Computation
# ===========
# read Energy Plus Weather data (file .EPW)
[data, meta] = read_epw(filename, coerce_year=2000)

# select outdoor air temperature; call it Î¸out
df = data[["temp_air"]]
del data
df = df.rename(columns={'temp_air': 'Î¸out'})

# Select the data for a period of the year
df = df.loc[period_start:period_end]
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m/var/folders/vp/k617ngs97xq4vlzlj5ts6sch0000gn/T/ipykernel_2489/891804606.py[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;31m# ===========[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;31m# read Energy Plus Weather data (file .EPW)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m [0;34m[[0m[0mdata[0m[0;34m,[0m [0mmeta[0m[0;34m][0m [0;34m=[0m [0mread_epw[0m[0;34m([0m[0mfilename[0m[0;34m,[0m [0mcoerce_year[0m[0;34m=[0m[0;36m2000[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0;34m[0m[0m
[1;32m      6[0m [0;31m# select outdoor air temperature; call it Î¸out[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/Personel/Py/git_book/dm4bem_book/docs/tutorials/dm4bem.py[0m in [0;36mread_epw[0;34m(filename, coerce_year)[0m
[1;32m    234[0m [0;34m[0m[0m
[1;32m    235[0m     [0;31m# Assume it's accessible via the file system[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 236[0;31m     [0mcsvdata[0m [0;34m=[0m [0mopen[0m[0;34m([0m[0mstr[0m[0;34m([0m[0mfilename[0m[0;34m)[0m[0;34m,[0m [0;34m'r'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    237[0m     [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    238[0m         [0mdata[0m[0;34m,[0m [0mmeta[0m [0;34m=[0m [0mparse_epw[0m[0;34m([0m[0mcsvdata[0m[0;34m,[0m [0mcoerce_year[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../weather_data/FRA_Lyon.074810_IWEC.epw'
FileNotFoundError: [Errno 2] No such file or directory: '../weather_data/FRA_Lyon.074810_IWEC.epw'

