Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# State matrix
As = -np.linalg.inv(C) @ A.T @ G @ A
pd.set_option('precision', 1)
pd.DataFrame(As, index=Î¸, columns=Î¸)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mOptionError[0m                               Traceback (most recent call last)
Cell [0;32mIn[17], line 3[0m
[1;32m      1[0m [38;5;66;03m# State matrix[39;00m
[1;32m      2[0m As [38;5;241m=[39m [38;5;241m-[39mnp[38;5;241m.[39mlinalg[38;5;241m.[39minv(C) [38;5;241m@[39m A[38;5;241m.[39mT [38;5;241m@[39m G [38;5;241m@[39m A
[0;32m----> 3[0m pd[38;5;241m.[39mset_option([38;5;124m'[39m[38;5;124mprecision[39m[38;5;124m'[39m, [38;5;241m1[39m)
[1;32m      4[0m pd[38;5;241m.[39mDataFrame(As, index[38;5;241m=[39mÎ¸, columns[38;5;241m=[39mÎ¸)

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/pandas/_config/config.py:272[0m, in [0;36mCallableDynamicDoc.__call__[0;34m(self, *args, **kwds)[0m
[1;32m    271[0m [38;5;28;01mdef[39;00m [38;5;21m__call__[39m([38;5;28mself[39m, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwds) [38;5;241m-[39m[38;5;241m>[39m T:
[0;32m--> 272[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m[38;5;18m__func__[39m([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwds)

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/pandas/_config/config.py:167[0m, in [0;36m_set_option[0;34m(*args, **kwargs)[0m
[1;32m    164[0m     [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m([38;5;124mf[39m[38;5;124m'[39m[38;5;124m_set_option() got an unexpected keyword argument [39m[38;5;124m"[39m[38;5;132;01m{[39;00mkwarg[38;5;132;01m}[39;00m[38;5;124m"[39m[38;5;124m'[39m)
[1;32m    166[0m [38;5;28;01mfor[39;00m k, v [38;5;129;01min[39;00m [38;5;28mzip[39m(args[::[38;5;241m2[39m], args[[38;5;241m1[39m::[38;5;241m2[39m]):
[0;32m--> 167[0m     key [38;5;241m=[39m _get_single_key(k, silent)
[1;32m    169[0m     o [38;5;241m=[39m _get_registered_option(key)
[1;32m    170[0m     [38;5;28;01mif[39;00m o [38;5;129;01mand[39;00m o[38;5;241m.[39mvalidator:

File [0;32m/opt/anaconda3/lib/python3.11/site-packages/pandas/_config/config.py:134[0m, in [0;36m_get_single_key[0;34m(pat, silent)[0m
[1;32m    132[0m     [38;5;28;01mraise[39;00m OptionError([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNo such keys(s): [39m[38;5;132;01m{[39;00m[38;5;28mrepr[39m(pat)[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m    133[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(keys) [38;5;241m>[39m [38;5;241m1[39m:
[0;32m--> 134[0m     [38;5;28;01mraise[39;00m OptionError([38;5;124m"[39m[38;5;124mPattern matched multiple keys[39m[38;5;124m"[39m)
[1;32m    135[0m key [38;5;241m=[39m keys[[38;5;241m0[39m]
[1;32m    137[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m silent:

[0;31mOptionError[0m: Pattern matched multiple keys

