Traceback (most recent call last):
  File "/Users/cghiaus/opt/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/cghiaus/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cghiaus/opt/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cghiaus/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/cghiaus/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/cghiaus/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/cghiaus/opt/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# plot results
y = pd.concat([y_exp, y_imp], axis=1, keys=['Explicit', 'Implicit'])
# Flatten the two-level column labels into a single level
y.columns = y.columns.get_level_values(0)

ax = y.plot()
ax.set_xlabel('Time')
ax.set_ylabel('Indoor temperature, $\\theta_i$ / Â°C')
ax.set_title(f'Time step: $dt$ = {dt:.0f} s; $dt_{{max}}$ = {dtmax:.0f} s')
plt.show()
------------------


[0;31m----------------------------------------------------------------------[0m
[0;31mNameError[0m                            Traceback (most recent call last)
Cell [0;32mIn[22], line 9[0m
[1;32m      7[0m ax[38;5;241m.[39mset_xlabel([38;5;124m'[39m[38;5;124mTime[39m[38;5;124m'[39m)
[1;32m      8[0m ax[38;5;241m.[39mset_ylabel([38;5;124m'[39m[38;5;124mIndoor temperature, $[39m[38;5;130;01m\\[39;00m[38;5;124mtheta_i$ / Â°C[39m[38;5;124m'[39m)
[0;32m----> 9[0m ax[38;5;241m.[39mset_title([38;5;124mf[39m[38;5;124m'[39m[38;5;124mTime step: $dt$ = [39m[38;5;132;01m{[39;00mdt[38;5;132;01m:[39;00m[38;5;124m.0f[39m[38;5;132;01m}[39;00m[38;5;124m s; $dt_[39m[38;5;130;01m{{[39;00m[38;5;124mmax[39m[38;5;130;01m}}[39;00m[38;5;124m$ = [39m[38;5;132;01m{[39;00mdtmax[38;5;132;01m:[39;00m[38;5;124m.0f[39m[38;5;132;01m}[39;00m[38;5;124m s[39m[38;5;124m'[39m)
[1;32m     10[0m plt[38;5;241m.[39mshow()

[0;31mNameError[0m: name 'dtmax' is not defined

