Traceback (most recent call last):
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/cghiaus/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
solar_protection = """
Tisp = 20   # indoor setpoint temperature, Â°C
Î”Î¸ = 1      # temperature deadband, Â°C
Kpp = 3e2   # controller gain

if Î¸_exp.iloc[k - 1]['c2_Î¸0'] < Tisp + Î”Î¸:
    u.iloc[k]['c2_Î¸0'] = 0
else:
    u.iloc[k]['c2_Î¸0'] = Kpp * (Tisp - Î¸_exp.iloc[k - 1]['c2_Î¸0'])
    u.iloc[k]['c2_Î¸0'] = min(u.iloc[k]['c2_Î¸0'], 0)
    u.iloc[k]['ow0_Î¸4'] *= 0.1
"""

period = ['05-01 12:00:00', '05-03 12:00:00']
control_for(solar, period)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/vp/k617ngs97xq4vlzlj5ts6sch0000gn/T/ipykernel_6920/2564080560.py[0m in [0;36m<module>[0;34m[0m
[1;32m     13[0m [0;34m[0m[0m
[1;32m     14[0m [0mperiod[0m [0;34m=[0m [0;34m[[0m[0;34m'05-01 12:00:00'[0m[0;34m,[0m [0;34m'05-03 12:00:00'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 15[0;31m [0mcontrol_for[0m[0;34m([0m[0msolar[0m[0;34m,[0m [0mperiod[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'solar' is not defined
NameError: name 'solar' is not defined

